version: 2.1
orbs:
    codecov: codecov/codecov@1.0.2
jobs:
    one:
        docker:
            # Specify the version you desire here
            - image: circleci/php:7.4-node-browsers

        steps:
            - checkout

            - run:
                name: "Prepare Environment"
                command: |
                    sudo apt update
                    sudo docker-php-ext-install zip

            - run:
                name: "Create Environment file"
                command: |
                    mv .env.testing .env

       
            # Download and cache dependencies
            - restore_cache:
                keys:
                #"composer.lock" can be used if it is committed to the repo
                - v1-dependencies-{{ checksum "composer.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

            - run:
                name: "Install Dependencies"
                command: composer install -n --prefer-dist
               

            - save_cache:
                key: v1-dependencies-{{ checksum "composer.json" }}
                paths:
                    - ./vendor

            #- run:
            #    name: "Generate App key"
            #    command: php artisan key:generate

            # run tests with phpunit
            - run:
                name: "Run Unit Tests"
#                 command: phpdbg -qrr vendor/bin/phpunit tests/unit --coverage-clover coverage.xml
                command: phpdbg -qrr vendor/bin/phpunit tests/unit --clover-xml coverage.xml
                
            - codecov/upload:
#                 file: ./vendor/bin/phpunit --coverage-clover=coverage.xml
                file: ./vendor/bin/phpunit --clover-xml=coverage.xml
                
#             - codecov/upload:
#                 file: coverage.xml
                
# #             - run: npm install
#             - run:
#                 name : Upload Codecov
#                 command: |
#                     echo "token" > .cc_token
#                     bash <(curl -s https://codecov.io/bash) -t @.cc_token
                    
#             - run:
#                 name: Upload Codecov
#                 command: |
#                     bash <(curl -s https://codecov.io/bash) -s coverage -d > upload.txt
#                     bash <(curl -s https://codecov.io/bash) -s coverage
    two:
        docker:
            - image: particleflux/circleci-bats-kcov:1.0.0
        steps:
            - checkout
            - run:
                name: Extract shunit
                command: tar zxvf shunit2-2.1.6.tgz
            # per https://github.com/SimonKagstrom/kcov/issues/45#issuecomment-68207360 this should work
            - run:
                name: Run Tests
                command: |
                    kcov --include-path=./codecov coverage/ tests/unit
            - run:
                name: Upload Codecov
                command: |
                    bash <(curl -s https://codecov.io/bash) -s coverage -d > upload.txt
                    bash <(curl -s https://codecov.io/bash) -s coverage
            - store_artifacts:
                path: codecov.txt
            - store_artifacts:
                path: coverage
                
workflows:
    version: 2.1
    one_and_two:
        jobs:
            - one
            - two
        
                

    
